spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql:///springboot
  username: root
  password: 123456


mybatis:
  typeAliasesPackage: com.pojo
  mapperLocations: classpath:mappers/*.xml
